export const RESTAURANT_DETAIL_REQUEST = 'RESTAURANT_DETAIL_REQUEST';
export const RESTAURANT_DETAIL_SUCCESS = 'RESTAURANT_DETAIL_SUCCESS';
export const RESTAURANT_DETAIL_FAIL = 'RESTAURANT_DETAIL_FAIL';